---
label: Development Agent

auto-provision: true
recreate-wallet: true

admin: [0.0.0.0, 8020]
admin-insecure-mode: true

inbound-transport:
   - [ws, 0:0:0:0:0:0:0:0, 8021]
   - [http, 0:0:0:0:0:0:0:0, 8022]
outbound-transport: [ws, http]

genesis-url: https://test.bcovrin.vonx.io/genesis
tails-server-base-url: https://tails-dev.vonx.io

wallet-type: askar
wallet-name: dev-agent-wallet
wallet-key: change-me

auto-ping-connection: true
auto-accept-invites: true
auto-accept-requests: true
auto-respond-messages: true

auto-store-credential: true

auto-respond-credential-offer: true
auto-respond-credential-request: true
auto-respond-credential-proposal: true

auto-verify-presentation: true
auto-respond-presentation-request: true

preserve-exchange-records: true

multitenant: true
jwt-secret: change-me
multitenant-admin: true

# plugin:
#   - webvh

# plugin-config-value:
#   - webvh.auto_config=false
#   - webvh.witness=false
#   - webvh.server_url=https://demo.identifier.me
